@url = http://localhost:50010

###
GET {{url}}/test

###
POST {{url}}/users/sign-up
Content-Type: application/json

{
    "email":"test@test.pl",
    "firstName":"Joe",
    "lastName":"Doe",
    "nickname":"JoeDoe99",
    "password":"Pass123!"
}

###
# @name sign_in
POST {{url}}/users/sign-in
Content-Type: application/json

{
    "email":"tomaszk@outlook.com",
    "password":"RUCH123nowe!"
}

###
@token = {{sign_in.response.body.$.token}}

###
GET {{url}}/users/me
Authorization: Bearer {{token}}